name: Deploy Lambda Function

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show all files in workspace (debug step)
        run: ls -R

      - name: Zip Lambda function (adjust path after running once)
        run: zip -j function.zip lambda_function.py || zip -j function.zip src/lambda_function.py || zip -j function.zip lambda_code/lambda_function.py

      - name: List contents of ZIP file
        run: unzip -l function.zip

      - name: Deploy to AWS Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SE_
